routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'auth', 'prefix' => 'prueba'], function (){
    Route::resource('auto', 'Autos');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

app/Auto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Auto extends Model
{
    public function marca()
    {
        return $this->belongsTo(\App\Marca::class);
    }

    public function scopeBuscar($query, $request)
    {
        if ($request->has('search')) {
            $search = '%' . $request->search . '%';
            return $query->where('nombre', 'like', $search)
                ->orWhereHas('marca', function ($query) use ($search) {
                    $query->where('nombre', 'like', $search);
                });
        }
    }

    function scopePorEdicion($query)
    {
        $query->orderBy('updated_at');
    }

    public
    function visitar()
    {
        $this->visitas++;
        $this->save();
    }
}

app/Marca.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Marca extends Model
{
    public function autos()
    {
        return $this->hasMany(\App\Auto::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Autos.php
<?php

namespace App\Http\Controllers;

use App\Auto;
use App\Http\Requests\AutosRequest;
use App\Events\AutoWasVisited;
use Illuminate\Http\Request;

class Autos extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $autos = Auto::buscar($request)->paginate(10);
        return view('autos.index', compact('autos', 'request'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $marcas = \App\Marca::get()->pluck('nombre', 'id')->toArray();
        return view('autos.create', compact('marcas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(AutosRequest $request)
    {
        $auto = new Auto();
        $auto->nombre = $request->nombre;
        $auto->marca_id = $request->marca;
        $auto->image = $request->file('image')->storePublicly('autos');
        $auto->save();

        return redirect()->route('auto.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show(Auto $auto)
    {
        if (!session('auto_visited_' . $auto->id)) {
            event(new AutoWasVisited($auto));
            session(['auto_visited_' . $auto->id => true]);
        }
        return view('autos.show', compact('auto'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Auto $auto)
    {
        $marcas = \App\Marca::get()->pluck('nombre', 'id')->toArray();
        return view('autos.edit', compact('auto', 'marcas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(AutosRequest $request, Auto $auto)
    {
        $auto->nombre = $request->nombre;
        $auto->marca_id = $request->marca;
        $auto->image = $request->file('image')->storePublicly('autos');
        $auto->save();

        return redirect()->route('auto.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Auto $auto)
    {
        $auto->delete();

        return redirect()->route('auto.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/autos/create.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="col-md-12">
      <div class="page-header">
        <h3>Agregar Autos</h3>
      </div>
      @section('formOpen')
        {!! Form::open(['route' => 'auto.store', 'enctype' => 'multipart/form-data']) !!}
      @show
      {!! Field::text('nombre', ['ph' => 'Nombre']) !!}
      {!! Field::select('marca', $marcas,['empty' => 'Marca']) !!}
      {!! Field::file('image') !!}
      <input class="btn btn-primary" type="submit" value="Guardar">
      <a class="btn btn-default" href="{{ route('auto.index') }}">Volver</a>
      {!! Form::close() !!}
    </div>
  </div>
@endsection

resources/views/autos/edit.blade.php
@extends('autos.create')

@section('formOpen')
  {!! Form::model($auto, ['route' => ['auto.update', $auto->id], 'method' => 'put', 'enctype' => 'multipart/form-data']) !!}
@endsection

resources/views/autos/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="col-md-12">
      <div class="page-header">
        <h3>Autos</h3>
      </div>
      <a class="btn btn-primary pull-right" href="{{ route('auto.create') }}">Nuevo auto</a>
      {!! Form::model($request, ['route' => 'auto.index', 'method' => 'get']) !!}
      {!! Field::text('search') !!}
      <input type="submit" value="buscar">
      {!! Form::close() !!}
      <table class="table table-responsive">
        <thead>
        <tr>
          <th></th>
          <th>Nombre</th>
          <th>Marca</th>
        </tr>
        </thead>
        <tbody>
        @foreach($autos as $auto)
          <tr>
            <td>
              <a class="btn btn-sm btn-default" href="{{ route('auto.show', $auto->id) }}">Ver</a>
              <a class="btn btn-sm btn-primary" href="{{ route('auto.edit', $auto->id) }}">Editar</a>
              {!! Form::open(['route' => ['auto.destroy', $auto->id], 'method' => 'delete']) !!}
              <input type="submit" class="btn btn-sm btn-danger" value="Eliminar">
              {!! Form::close() !!}
            </td>
            <td>{{ $auto->nombre }}</td>
            <td>{{ $auto->marca->nombre }}</td>
          </tr>
        @endforeach
        </tbody>
      </table>
      {!! $autos->links() !!}
    </div>
  </div>
@endsection

resources/views/autos/show.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="col-md-12">
      <div class="page-header">
        <h3>Autos</h3>
      </div>
      <ul>
        <li>{{ $auto->nombre }}</li>
        <li>{{ $auto->marca->nombre }}</li>
        <li><img src="{{ asset('storage/'.$auto->image) }}" alt="{{ asset('storage/'.$auto->image) }}"></li>
      </ul>
      <a class="btn btn-default" href="{{ route('auto.index') }}">Volver</a>
    </div>
  </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">

  <title>{{ config('app.name', 'Laravel') }}</title>

  <!-- Styles -->
  <link href="{{ asset('/css/app.css') }}" rel="stylesheet">

  <!-- Scripts -->
  <script>
    window.Laravel = <?php echo json_encode([
        'csrfToken' => csrf_token(),
    ]); ?>
  </script>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">

      <!-- Collapsed Hamburger -->
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <!-- Branding Image -->
      <a class="navbar-brand" href="{{ url('/') }}">
        {{ config('app.name', 'Laravel') }}
      </a>
    </div>

    <div class="collapse navbar-collapse" id="app-navbar-collapse">
      <!-- Left Side Of Navbar -->
      <ul class="nav navbar-nav">
        &nbsp;
      </ul>

      <!-- Right Side Of Navbar -->
      <ul class="nav navbar-nav navbar-right">
        <!-- Authentication Links -->
        @if (Auth::guest())
          <li><a href="{{ url('/login') }}">Login</a></li>
          <li><a href="{{ url('/register') }}">Register</a></li>
        @else
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              {{ Auth::user()->name }} <span class="caret"></span>
            </a>

            <ul class="dropdown-menu" role="menu">
              <li>
                <a href="{{ url('/logout') }}"
                   onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                  Logout
                </a>

                <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                  {{ csrf_field() }}
                </form>
              </li>
            </ul>
          </li>
        @endif
      </ul>
    </div>
  </div>
</nav>

@yield('content')

<!-- Scripts -->
<script src="{{ asset('/js/app.js') }}"></script>

@yield('pageScript')
</body>
</html>